# Running LAMP on a Metabolon study (MTBLS533)

In [1]:
import sqlite3
import pandas as pd
from lamp import anno, stats, utils

In [8]:
!curl -o ./MTBLS533_xcms_variableMetadata.tsv https://metabolights-labs.org/api/datasets/3ef22a121f514926/display?to_ext=tabular

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  270k    0  2491    0     0  30479      0  0:00:09 --:--:--  0:00:09 31531
100  270k  100  270k    0     0  2489k      0 --:--:-- --:--:-- --:--:-- 2554k

In [4]:
!curl -o ./MTBLS533_xcms_dataMatrix.tsv https://metabolights-labs.org/api/datasets/3f62c0fbd60427f3/display?to_ext=tabular

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  447k  100  447k    0     0  2897k      0 --:--:-- --:--:-- --:--:-- 3022k

In [3]:
# data set
d_data = "MTBLS533_xcms_variableMetadata.tsv"
data = pd.read_table(d_data, header=0, sep="\t")
data

,name,namecustom,mz,mzmin,mzmax,rt,rtmin,rtmax,npeaks,.,peakidx,ms_level
0,M70T65,M70.0294T64.591,70.029390,70.029346,70.029451,64.590973,48.365021,64.962372,25,24,"1021,2671,3483,5090,5842,7439,8182,8251,9028,9...",1
1,M70T87,M70.0659T87.2182,70.065851,70.065817,70.065877,87.218224,86.785202,87.534653,36,36,"330,1139,2008,2777,3615,4400,5223,5968,6754,75...",1
2,M71T41,M71.0734T40.6038,71.073382,71.072987,71.073658,40.603788,39.642391,41.711369,34,34,"916,1743,2568,3373,4161,4974,5733,6499,7309,81...",1
3,M72T142,M72.0815T142.4226,72.081495,72.081474,72.081538,142.422630,141.759628,143.071512,36,36,"547,1325,2192,2973,3806,4591,5591,6149,6947,77...",1
4,M72T177,M72.0815T176.5532,72.081506,72.081447,72.081548,176.553231,176.131592,176.804352,36,36,"759,1575,2415,3208,4018,4818,5592,6338,7155,79...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
985,M897T78,M896.9188T78.1688,896.918799,896.918126,896.919142,78.168812,77.420700,78.660957,36,36,"268,1082,1954,2729,3554,4346,5165,5904,6697,74...",1
986,M898T78,M897.9218T78.1369,897.921772,897.921147,897.922166,78.136944,77.420700,78.660957,24,24,"1079,1951,2727,3549,5161,7493,8310,9091,9853,1...",1
987,M920T31,M920.1419T30.8599,920.141933,920.141521,920.142435,30.859859,30.520224,31.171314,15,15,"4112,4909,5680,8067,8837,13398,14202,14995,165...",1
988,M949T174,M948.9518T174.4722,948.951762,948.950817,948.952906,174.472191,174.152344,174.847015,26,26,"589,1362,2234,3011,3841,4627,5447,6171,6972,85...",1
989,M965T174,M964.9254T174.0387,964.925424,964.924061,964.927369,174.038696,173.708038,174.414520,26,26,"590,1363,2235,3008,3842,4622,5442,6169,6973,77...",1

In [5]:
variableMetadata = pd.read_table("MTBLS533_xcms_variableMetadata.tsv", header=0, sep="\t")
dataMatrix = pd.read_table("MTBLS533_xcms_dataMatrix.tsv", header=0, sep="\t")

In [13]:
variableMetadata

,name,namecustom,mz,mzmin,mzmax,rt,rtmin,rtmax,npeaks,.,peakidx,ms_level
0,M70T65,M70.0294T64.591,70.029390,70.029346,70.029451,64.590973,48.365021,64.962372,25,24,"1021,2671,3483,5090,5842,7439,8182,8251,9028,9...",1
1,M70T87,M70.0659T87.2182,70.065851,70.065817,70.065877,87.218224,86.785202,87.534653,36,36,"330,1139,2008,2777,3615,4400,5223,5968,6754,75...",1
2,M71T41,M71.0734T40.6038,71.073382,71.072987,71.073658,40.603788,39.642391,41.711369,34,34,"916,1743,2568,3373,4161,4974,5733,6499,7309,81...",1
3,M72T142,M72.0815T142.4226,72.081495,72.081474,72.081538,142.422630,141.759628,143.071512,36,36,"547,1325,2192,2973,3806,4591,5591,6149,6947,77...",1
4,M72T177,M72.0815T176.5532,72.081506,72.081447,72.081548,176.553231,176.131592,176.804352,36,36,"759,1575,2415,3208,4018,4818,5592,6338,7155,79...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
985,M897T78,M896.9188T78.1688,896.918799,896.918126,896.919142,78.168812,77.420700,78.660957,36,36,"268,1082,1954,2729,3554,4346,5165,5904,6697,74...",1
986,M898T78,M897.9218T78.1369,897.921772,897.921147,897.922166,78.136944,77.420700,78.660957,24,24,"1079,1951,2727,3549,5161,7493,8310,9091,9853,1...",1
987,M920T31,M920.1419T30.8599,920.141933,920.141521,920.142435,30.859859,30.520224,31.171314,15,15,"4112,4909,5680,8067,8837,13398,14202,14995,165...",1
988,M949T174,M948.9518T174.4722,948.951762,948.950817,948.952906,174.472191,174.152344,174.847015,26,26,"589,1362,2234,3011,3841,4627,5447,6171,6972,85...",1
989,M965T174,M964.9254T174.0387,964.925424,964.924061,964.927369,174.038696,173.708038,174.414520,26,26,"590,1363,2235,3008,3842,4622,5442,6169,6973,77...",1

In [7]:
dataMatrix.head()

,name,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_03,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_04,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_05,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_06,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_07,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_08,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_09,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_10,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_11,...,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_31,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_32,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_33,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_35,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_36,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_37,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_38,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_39,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_40,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_42
0,M70T65,0.000000e+00,1.174471e+06,0.000000e+00,9.163649e+05,1.244338e+06,0.000000e+00,1.124845e+06,1.139561e+06,0.000000e+00,...,0.000000e+00,8.231199e+05,1.913921e+06,0.000000e+00,1.103076e+06,0.000000e+00,8.717383e+05,0.000000e+00,7.555283e+05,1.542717e+06
1,M70T87,2.101240e+08,1.028818e+08,1.390223e+08,7.456752e+07,1.787382e+08,2.507514e+08,1.819825e+08,1.817377e+08,2.017396e+08,...,1.975596e+08,2.455242e+08,1.916901e+08,1.627301e+08,9.824233e+07,1.872480e+08,6.930313e+07,2.440454e+08,7.159298e+07,2.244917e+08
2,M71T41,0.000000e+00,1.578996e+06,9.222626e+05,8.212176e+05,5.047038e+06,4.222885e+06,4.798458e+06,4.138945e+06,1.130255e+06,...,4.107745e+06,3.533100e+06,3.876297e+06,4.074572e+06,1.164178e+06,1.162641e+06,1.020634e+06,3.983264e+06,7.271866e+05,2.702986e+06
3,M72T142,1.114087e+08,4.945979e+07,8.693694e+07,5.004008e+07,1.603943e+08,2.017597e+08,1.635450e+08,1.517630e+08,1.084847e+08,...,1.963106e+08,2.184193e+08,2.048691e+08,1.322462e+08,5.180773e+07,1.077916e+08,5.405562e+07,2.156591e+08,5.195452e+07,3.002943e+08
4,M72T177,7.949030e+07,7.971405e+07,7.796347e+07,7.747577e+07,7.135565e+07,7.726693e+07,7.675308e+07,7.512268e+07,7.500802e+07,...,7.364368e+07,7.390618e+07,7.442212e+07,7.432736e+07,7.148519e+07,7.075092e+07,7.669908e+07,7.781515e+07,7.484561e+07,8.910621e+07

In [8]:
# merge the intensity data with the feature metadata
xcms_data = pd.merge(variableMetadata, dataMatrix, on="name")

In [26]:
xcms_data.to_csv("xcms_data.tsv", index=False, sep="\t")

In [9]:
xcms_data

,name,namecustom,mz,mzmin,mzmax,rt,rtmin,rtmax,npeaks,.,...,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_31,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_32,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_33,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_35,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_36,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_37,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_38,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_39,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_40,QXA10POSEAR20170601_UWIM0317VW_HUMAN_CELLS_42
0,M70T65,M70.0294T64.591,70.029390,70.029346,70.029451,64.590973,48.365021,64.962372,25,24,...,0.000000e+00,8.231199e+05,1.913921e+06,0.000000e+00,1.103076e+06,0.000000e+00,8.717383e+05,0.000000e+00,7.555283e+05,1.542717e+06
1,M70T87,M70.0659T87.2182,70.065851,70.065817,70.065877,87.218224,86.785202,87.534653,36,36,...,1.975596e+08,2.455242e+08,1.916901e+08,1.627301e+08,9.824233e+07,1.872480e+08,6.930313e+07,2.440454e+08,7.159298e+07,2.244917e+08
2,M71T41,M71.0734T40.6038,71.073382,71.072987,71.073658,40.603788,39.642391,41.711369,34,34,...,4.107745e+06,3.533100e+06,3.876297e+06,4.074572e+06,1.164178e+06,1.162641e+06,1.020634e+06,3.983264e+06,7.271866e+05,2.702986e+06
3,M72T142,M72.0815T142.4226,72.081495,72.081474,72.081538,142.422630,141.759628,143.071512,36,36,...,1.963106e+08,2.184193e+08,2.048691e+08,1.322462e+08,5.180773e+07,1.077916e+08,5.405562e+07,2.156591e+08,5.195452e+07,3.002943e+08
4,M72T177,M72.0815T176.5532,72.081506,72.081447,72.081548,176.553231,176.131592,176.804352,36,36,...,7.364368e+07,7.390618e+07,7.442212e+07,7.432736e+07,7.148519e+07,7.075092e+07,7.669908e+07,7.781515e+07,7.484561e+07,8.910621e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,M897T78,M896.9188T78.1688,896.918799,896.918126,896.919142,78.168812,77.420700,78.660957,36,36,...,1.715022e+07,1.983935e+07,1.889477e+07,2.278157e+07,1.431852e+07,1.511719e+07,1.037583e+07,2.102882e+07,1.025318e+07,1.295407e+07
986,M898T78,M897.9218T78.1369,897.921772,897.921147,897.922166,78.136944,77.420700,78.660957,24,24,...,0.000000e+00,4.867235e+06,0.000000e+00,5.700977e+06,3.512191e+06,3.626571e+06,2.648702e+06,0.000000e+00,2.547560e+06,3.201827e+06
987,M920T31,M920.1419T30.8599,920.141933,920.141521,920.142435,30.859859,30.520224,31.171314,15,15,...,1.588948e+06,1.715710e+06,1.561852e+06,1.245329e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.029894e+06
988,M949T174,M948.9518T174.4722,948.951762,948.950817,948.952906,174.472191,174.152344,174.847015,26,26,...,3.229177e+06,3.535069e+06,3.630036e+06,3.229787e+06,0.000000e+00,2.734277e+06,0.000000e+00,3.483595e+06,0.000000e+00,3.391954e+06
989,M965T174,M964.9254T174.0387,964.925424,964.924061,964.927369,174.038696,173.708038,174.414520,26,26,...,9.990353e+05,0.000000e+00,9.199239e+05,0.000000e+00,1.060882e+06,1.044128e+06,1.060087e+06,0.000000e+00,0.000000e+00,0.000000e+00

In [10]:
ref_path = ""

In [11]:
ref = anno.read_ref(ref_path, calc=False)
ref

,compound_id,molecular_formula,compound_name,exact_mass
0,1638,C10Cl10O,Chlordecone,485.683441
1,38485,C10H10Br2O2,Dibromothymoquinone,319.904755
2,32427,C10H10BrNO2,Brofoxine (USAN/INN),254.989491
3,39834,C10H10Cl2N2O,Fenmetozole (USAN),244.017018
4,10156,C10H10Cl2O3,"4-(2,4-Dichlorophenoxy)butyric acid",248.000700
...,...,...,...,...
31639,80256,H5O10P3,PPPi,257.909557
31640,37374,H6NO9P3,(Diphosphono)Aminophosphonic Acid,256.925542
31641,32626,H9N2O4P,Ammonium phosphate (NF),132.029994
31642,735,HNO3,Nitrate,62.995643
31643,40762,HNO3,Peroxynitrite,62.995643

In [15]:
ppm = 5.0
cols = [1, 3, 6, 13]
match = anno.comp_match_mass(xcms_data, ppm, ref)
match

,id,mz,compound_id,molecular_formula,compound_name,exact_mass,ppm_error
0,M71T41,71.073382,9110,C4H9N,3-Buten-1-amine,71.07,-1.64
1,M82T151,82.052902,41915,C4H6N2,1-Methylimidazole,82.05,-2.39
2,M82T151,82.052902,37597,C4H6N2,4-Methylimidazole,82.05,-2.39
3,M82T151,82.052902,5052,C4H6N2,Fomepizole,82.05,-2.39
4,M116T37,116.010935,1832,C4H4O4,Formylpyruvate,116.01,-0.21
...,...,...,...,...,...,...,...
285,M473T40,473.165680,12349,C20H23N7O7,N10-Formyl-THF,473.17,-0.46
286,M473T40,473.165680,20470,C20H23N7O7,N5-formyl-THF,473.17,-0.46
287,M473T40,473.165680,12635,C20H23N7O7,Pteroyl-D-glutamic acid,473.17,-0.46
288,M473T40,473.165680,4599,C28H27NO4S,Raloxifene,473.17,-0.84
289,M489T41,489.114321,40744,C16H27NO14S,Chondroitin 4-sulfate,489.12,-1.85

In [18]:
ion_mode = "pos"
# if empty, use default adducts library
add_path = ""
lib_add = anno.read_lib(add_path, ion_mode)
lib_add

                      label  exact_mass  charge
0                    [M+H]+    1.007276       1
1                  [M+NH4]+   18.033826       1
2                   [M+Na]+   22.989221       1
3                   [M+Mg]+   23.984493       1
4                    [M+K]+   38.963158       1
5                   [M+Fe]+   55.934388       1
6                   [M+Cu]+   62.929049       1
7                   [M+2H]+    2.015101       1
8                   [M+3H]+    3.022926       1
9             [M+NaFormate]   67.987400       1
10  [M+NaFormate+NaFormate]  135.974800       1
11                 [M+NaCl]   57.958600       1
12          [M+Formic acid]   46.000500       1
13         [M+Acetonitrile]   41.026500       1
14            [M+CaFormate]   84.960300       1

In [19]:
match_1 = anno.comp_match_mass_add(xcms_data, ppm, ref, lib_add)
match_1

,id,mz,compound_id,molecular_formula,compound_name,exact_mass,adduct,ppm_error
0,M82T151,82.052902,828,C4H4N2,Pyrimidine,82.05,[M+2H]+,4.30
1,M82T151,82.052902,38274,C2H3N,Methyl Isocyanide,82.05,[M+Acetonitrile],-1.79
2,M98T77,98.021758,1171,C3H6O2,3-Hydroxypropanal,98.02,[M+Mg]+,4.96
3,M98T77,98.021758,7909,C3H6O2,Glycidol,98.02,[M+Mg]+,4.96
4,M98T77,98.021758,3324,C3H6O2,Hydroxyacetone,98.02,[M+Mg]+,4.96
...,...,...,...,...,...,...,...,...
6907,M965T174,964.925424,23530,C61H118O6,TG(17:0/20:0/21:0)[iso6],964.93,[M+NH4]+,-1.29
6908,M965T174,964.925424,23476,C61H118O6,TG(18:0/18:0/22:0)[iso3],964.93,[M+NH4]+,-1.29
6909,M965T174,964.925424,23666,C61H118O6,TG(18:0/19:0/21:0)[iso6],964.93,[M+NH4]+,-1.29
6910,M965T174,964.925424,13271,C61H118O6,TG(18:0/20:0/20:0)[iso3],964.93,[M+NH4]+,-1.29
6911,M965T174,964.925424,23502,C61H118O6,TG(19:0/19:0/20:0)[iso3],964.93,[M+NH4]+,-1.29

In [20]:
thres_rt = 1.0
thres_corr = 0.5
thres_pval = 0.05
method = "spearman"  # "pearson"
positive = True

In [22]:
utils._tic()
corr = stats.comp_corr_rt(xcms_data, thres_rt, thres_corr, thres_pval, method,
                          positive)
utils._toc()
corr

TypeError: '<' not supported between instances of 'str' and 'float'

In [23]:
# get summary of metabolite annotation
sr, mr = anno.comp_summ(xcms_data, match)

In [24]:
sr

,name,mz,rt,compound_id,exact_mass,ppm_error,molecular_formula,compound_name
0,M100T171,100.112526,171.058777,NaN,NaN,NaN,NaN,NaN
1,M101T36,100.988837,36.103134,NaN,NaN,NaN,NaN,NaN
2,M101T63,101.023746,62.512497,NaN,NaN,NaN,NaN,NaN
3,M101T72,101.071293,72.108711,NaN,NaN,NaN,NaN,NaN
4,M102T158,102.128117,158.461380,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
985,M97T35,97.028952,35.169632,NaN,NaN,NaN,NaN,NaN
986,M97T53,97.028967,52.970959,NaN,NaN,NaN,NaN,NaN
987,M98T77,98.021758,76.768524,NaN,NaN,NaN,NaN,NaN
988,M99T181,98.984272,180.539711,NaN,NaN,NaN,NaN,NaN
989,M99T37,98.984563,36.581100,NaN,NaN,NaN,NaN,NaN

In [25]:
# merge summery table with correlation analysis
res = anno.comp_summ_corr(sr, corr_df)
res

NameError: name 'corr_df' is not defined